---
dapp_freeipa_docker_image: "docker.io/freeipa/freeipa-server:almalinux-9-4.11.0"

# freeipa docker environment variables
dapp_freeipa_docker_environment: |
  {{ dapp_common_docker_environment }}
  #DEBUG_TRACE: 1
  #DEBUG_NO_EXIT: 1

dapp_freeipa_dns_servers:
  - 1.1.1.1
  - 8.8.8.8
  - 9.9.9.9

# freeipa directory server/manager password
# dapp_freeipa_pwd_dm: <secret>

# freeipa admin password
# dapp_freeipa_pwd_admin: <secret>

# Optional certificate for HTTP and Directory server
# 'pin' is the password to encrypt the HTTP and Directory server private key
# dapp_freeipa_cert:
#   crt: <changeme>
#   key: <secret>
#   pin: <secret>

# The following variables should probably be defined in group_vars/all.yml
# as they are used in several roles and playbooks.
dapp_freeipa_realm: "{{ dapp_common_domain }}"
dapp_freeipa_domain: "{{ dapp_common_domain }}"

# dapp_freeipa_server_master: "ipa1.{{ dapp_common_domain }}"

# If you have 3 freeipa server, you can define replica1 and
# replica2 to set Domain & CA replication between them.
# dapp_freeipa_server_replica1: "ipa2.{{ dapp_common_domain }}"
# dapp_freeipa_server_replica2: "ipa3.{{ dapp_common_domain }}"

# do not validate self-signed certificates
dapp_freeipa_validate_certs: false

# configure freeipa with traefik proxy
dapp_freeipa_traefik: false

# server name to access freeipa web using traefik & let's encrypt
dapp_freeipa_https_traefik_address: "ipa.{{ dapp_common_domain }}"

# server name to access freeipa ldaps using traefik & let's encrypt
dapp_freeipa_ldaps_traefik_address: "ldap.{{ dapp_common_domain }}"

dapp_freeipa_ports:
  # dns
  #- "53:53/tcp"     # if you want freeipa as dns server
  #- "53:53/udp"
  # web
  - "80:80/tcp"      # if your using traefik, open 80 in traefik container instead
  - "443:443/tcp"    # if your using traefik, open 443 in traefik container instead
  # kerberos
  - "88:88/tcp"
  - "88:88/udp"
  - "464:464/tcp"
  - "464:464/udp"
  # ntp
  #- "123:123/udp"   # if you want freeipa as ntp server
  # ldap
  - "389:389/tcp"
  - "636:636/tcp"    # if your using traefik, open 636 in traefik container instead


# Use file provider to add a serversTransports for connection between traefik proxy
# and freeipa service. freeipa forces https so traefik must accept freeipa's selfsigned certificate.
dapp_common_traefik_file_provider: |
  http:
    serversTransports:
      freeipa:
        serverName: "{{ dapp_freeipa_hostname }}.{{ dapp_common_domain }}"
        insecureSkipVerify: "true"

# freeipa installation commands
dapp_freeipa_command_master: |
  ipa-server-install --admin-password='{{ dapp_freeipa_pwd_admin }}' --ds-password='{{ dapp_freeipa_pwd_dm }}' --domain={{ dapp_freeipa_realm }} --realm={{ dapp_freeipa_realm | upper }} --unattended --no-hbac-allow --no-ntp --skip-mem-check

dapp_freeipa_command_replica: |
  ipa-replica-install --admin-password='{{ dapp_freeipa_pwd_admin }}' --domain={{ dapp_freeipa_domain }} --realm={{ dapp_freeipa_realm | upper }} --server={{ dapp_freeipa_server_master }} --hostname={{ dapp_freeipa_hostname }}.{{ dapp_common_domain }} --unattended --no-ntp --setup-ca --skip-mem-check

# If you have defined a certificate in 'dapp_freeipa_cert', you must add the following parameters to the above commands.
# --no-pkinit --http-pin {{ dapp_freeipa_cert.pin }} --dirsrv-pin {{ dapp_freeipa_cert.pin }} --http-cert-file /etc/pki/CA/certs/freeipa_cert.crt --http-cert-file /etc/pki/CA/private/freeipa_cert.key --dirsrv-cert-file /etc/pki/CA/certs/freeipa_cert.crt --dirsrv-cert-file /etc/pki/CA/private/freeipa_cert.key
