---
networks:
  traefik_proxy:
    external: true
services:
  app:
    image: "{{ docker_apps_image_homepage }}"
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: "homepage"
    networks:
      - traefik_proxy
    mem_limit: 128M
    environment:
      TZ: "America/New_York"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./bookmarks.yaml:/app/config/bookmarks.yaml"
      - "./services.yaml:/app/config/services.yaml"
      - "./settings.yaml:/app/config/settings.yaml"
      - "./widgets.yaml:/app/config/widgets.yaml"
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik_proxy"
      traefik.http.routers.homepage.entrypoints: "http, https"
      traefik.http.routers.homepage.rule: "Host(`{{ traefik_address_homepage }}`)"
      traefik.http.services.homepage.loadbalancer.server.port: "3000"
{% if common_traefik_tls %}
      traefik.http.routers.homepage.tls: "true"
{% endif %}
{% if common_traefik_tls and common_traefik_certresolver != "none" %}
      traefik.http.routers.homepage.tls.certresolver: "{{ common_traefik_certresolver }}"
      traefik.http.routers.homepage.tls.domains[0].main: "{{ traefik_address_homepage }}"
{% endif %}
