---
- name: Set project directory
  ansible.builtin.set_fact:
    _docker_project_dir: "{{ dapp_common_directory }}/{{ role_name }}"

- name: Create project directory
  ansible.builtin.file:
    path: "{{ _docker_project_dir }}"
    state: directory

- name: Copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ _docker_project_dir }}/docker-compose.yml"
    mode: "0640"

- name: Copy Dockerfile
  ansible.builtin.copy:
    dest: "{{ _docker_project_dir }}/Dockerfile"
    content: "{{ dapp_rsyslog_dockerfile }}"
  notify: Rebuild containers

- name: Copy entrypoint.sh
  ansible.builtin.copy:
    dest: "{{ _docker_project_dir }}/entrypoint.sh"
    content: "{{ dapp_rsyslog_entrypoint }}"
    mode: "0755"
  notify: Restart containers

- name: Copy rsyslog.conf
  ansible.builtin.copy:
    dest: "{{ _docker_project_dir }}/rsyslog.conf"
    content: "{{ dapp_rsyslog_conf }}"
    mode: "0644"
  notify: Restart containers

- name: Start containers
  ansible.builtin.shell: |
    docker compose --project-directory "{{ _docker_project_dir }}" up -d
  changed_when: false

- name: Set daily cronjob for file compression
  ansible.builtin.cron:
    hour: "{{ dapp_rsyslog_compress_cron_hour }}"
    job: "{{ dapp_rsyslog_compress_cron_job }}"
    minute: "{{ dapp_rsyslog_compress_cron_minute }}"
    name: dapp_rsyslog_compress_cron
    state: "{{ dapp_rsyslog_compress_cron_state }}"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
