---
# docker images
gitlab_docker_image: "docker.io/gitlab/gitlab-ce"
gitlab_runner_docker_image: "docker.io/gitlab/gitlab-runner"

# gitlab server address
gitlab_traefik_address: "gitlab.{{ common_apps_domain }}"

gitlab_mem_limit: 4096M
gitlab_runner_mem_limit: 3072M

gitlab_cpus: 2
gitlab_runner_cpus: 2

# gitlab external ssh port
gitlab_shell_ssh_port: 2222
gitlab_ports:
  - "{{ gitlab_shell_ssh_port }}:22"

# https://docs.gitlab.com/omnibus/settings/logs.html
# https://docs.gitlab.com/ee/administration/logs/index.html
gitlab_log_level: ERROR

# Configuration settings using the Omnibus package
# https://docs.gitlab.com/omnibus/settings/configuration.html
# https://docs.gitlab.com/omnibus/settings/memory_constrained_envs.html
gitlab_omnibus_config: |
  external_url 'https://{{ gitlab_traefik_address }}'
  gitlab_rails['gitlab_shell_ssh_port'] = {{ gitlab_shell_ssh_port }}
  gitlab_shell['log_level'] = '{{ gitlab_log_level }}'
  nginx['listen_https'] = false
  nginx['listen_port'] = 80
  prometheus_monitoring['enable'] = false
  puma['worker_processes'] = 0
  registry['log_level'] = '{{ gitlab_log_level }}'
  sidekiq['max_concurrency'] = 10
  sidekiq['metrics_enabled'] = false
  gitlab_rails['env'] = {
    "GITLAB_LOG_LEVEL" => "{{ gitlab_log_level }}",
    "DEBUG" => "{{ gitlab_log_level }}",
    "VERBOSE" => "{{ gitlab_log_level }}",
    "EXPORT_DEBUG" => "{{ gitlab_log_level }}",
    "IMPORT_DEBUG" => "{{ gitlab_log_level }}",
    "QA_LOG_LEVEL" => "{{ gitlab_log_level }}",
    "GRPC_LOG_LEVEL" => "{{ gitlab_log_level }}",
    "LLM_DEBUG" => "{{ gitlab_log_level }}",
    "MALLOC_CONF" => "dirty_decay_ms:1000,muzzy_decay_ms:1000"
  }
  gitaly['configuration'] = {
    concurrency: [
      {
        'rpc' => "/gitaly.SmartHTTPService/PostReceivePack",
        'max_per_repo' => 3,
      }, {
        'rpc' => "/gitaly.SSHService/SSHUploadPack",
        'max_per_repo' => 3,
      },
    ],
    logging: {
      level: "{{ gitlab_log_level }}"
    },
  }
  gitaly['env'] = {
    'GITALY_COMMAND_SPAWN_MAX_PARALLEL' => '2',
    'MALLOC_CONF' => 'dirty_decay_ms:1000,muzzy_decay_ms:1000'
  }

gitlab_runner_dockerfile: |
  # Dockerfile to build the gitlab runner container
  FROM debian:12
  ENV DEBIAN_FRONTEND=noninteractive
  RUN <<EOF
  /usr/bin/apt-get update
  /usr/bin/apt-get -y upgrade
  /usr/bin/apt-get -y dist-upgrade
  /usr/bin/apt-get -y install \
    --no-install-recommends --no-install-suggests \
    ansible ansible-lint coreutils curl git jq openssh-client \
    python3 python3-dev tar wget python3-dnspython python3-netaddr python3-pip
  /usr/bin/apt-get clean
  mkdir -p -m 0700 ~/.ssh
  echo "StrictHostKeyChecking no\n" > ~/.ssh/config
  EOF
