---
# main directory for docker apps project. (relative to docker_rootless_home)
dapp_common_directory: docker

# common docker environment variables
dapp_common_docker_environment: |
  TZ: "America/New_York"

# dns domain name for traefik rules and let's encrypt certificate management.
dapp_common_domain: localdomain

# configure traefik with tls and certificates
dapp_common_traefik_tls: true

# cert resolver for traefik & let's encrypt
# set to 'none' if you already have your certificate and/or using self-signed certificate.
dapp_common_traefik_certresolver: none

# for let's encrypt, set the 'certresolver' to something else than 'none'.
# and look at 'docker_apps/roles/traefik/defaults/main.yml' for an example of
# how to set a provider from https://go-acme.github.io/lego/dns/
# dapp_common_traefik_certresolver: mydomain

# You can add Traefik configuration using file provider.
# https://doc.traefik.io/traefik/providers/file/
# dapp_common_traefik_file_provider: |
#   http:
#     serversTransports:
#       mytransport:
#         serverName: "myhost"
