---
# docker image
dapp_privatebin_docker_image: "docker.io/privatebin/nginx-fpm-alpine"

# privatebin docker environment variables
dapp_privatebin_docker_environment: |
  {{ dapp_common_docker_environment }}

# privatebin server address
dapp_privatebin_traefik_address: "privatebin.{{ dapp_common_domain }}"
