{
 "title": "Linux - Node Exporter Server Metrics",
 "description": "Dashboard to view multiple servers. https://grafana.com/grafana/dashboards/405",
 "tags": [
  "node_exporter",
  "compare",
  "multi",
  "grafana.com"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "node",
    "query": "label_values(node_exporter_build_info, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Load - $node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "load"
    }
   ]
  },
  {
   "title": "CPU / Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Cores",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 15 },
     "repeat": "node",
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu))"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "repeat": "node",
     "yaxes": [
      { "format": "short", "label": "%" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"system\",instance=~'$node'}[5m]))",
       "legendFormat": "system"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\",instance=~'$node'}[5m]))",
       "legendFormat": "user"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"nice\",instance=~'$node'}[5m]))",
       "legendFormat": "nice"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"iowait\",instance=~'$node'}[5m]))",
       "legendFormat": "iowait"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"steal\",instance=~'$node'}[5m]))",
       "legendFormat": "steal"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\",instance=~'$node'}[5m]))",
       "legendFormat": "idle"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"irq\",instance=~'$node'}[5m]))",
       "legendFormat": "irq"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"softirq\",instance=~'$node'}[5m]))",
       "legendFormat": "softirq"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{mode=\"guest\",instance=~'$node'}[5m]))",
       "legendFormat": "guest"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "repeat": "node",
     "yaxes": [
      { "format": "bytes", "label": "GB" }
     ],
     "targets": [
      {
       "expr": "( node_memory_MemTotal_bytes{instance=~'$node'} - node_memory_MemFree_bytes{instance=~'$node'} - node_memory_Buffers_bytes{instance=~'$node'} - node_memory_Cached_bytes{instance=~'$node'} - node_memory_SwapCached_bytes{instance=~'$node'} - node_memory_Slab_bytes{instance=~'$node'} - node_memory_PageTables_bytes{instance=~'$node'} - node_memory_VmallocUsed_bytes{instance=~'$node'} )",
       "legendFormat": "Apps"
      },
      {
       "expr": "node_memory_Buffers_bytes{instance=~'$node'}",
       "legendFormat": "Buffers"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=~'$node'}",
       "legendFormat": "Cached"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=~'$node'}",
       "legendFormat": "Free"
      },
      {
       "expr": "node_memory_Slab_bytes{instance=~'$node'}",
       "legendFormat": "Slab"
      },
      {
       "expr": "node_memory_SwapCached_bytes{instance=~'$node'}",
       "legendFormat": "SwapCached"
      },
      {
       "expr": "node_memory_PageTables_bytes{instance=~'$node'}",
       "legendFormat": "PageTables"
      },
      {
       "expr": "node_memory_VmallocUsed_bytes{instance=~'$node'}",
       "legendFormat": "VmallocUsed"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=~'$node'} - node_memory_SwapFree{instance=~'$node'})",
       "legendFormat": "Swap"
      },
      {
       "expr": "node_memory_Committed_AS_bytes{instance=~'$node'}",
       "legendFormat": "Committed"
      },
      {
       "expr": "node_memory_Mapped_bytes{instance=~'$node'}",
       "legendFormat": "Mapped"
      },
      {
       "expr": "node_memory_Active_bytes{instance=~'$node'}",
       "legendFormat": "Active"
      },
      {
       "expr": "node_memory_Inactive_bytes{instance=~'$node'}",
       "legendFormat": "Inactive"
      }
     ]
    },
    {
     "title": "Context Switches",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
     "repeat": "node",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(node_context_switches_total{instance=~\"$node\"}[5m])",
       "legendFormat": "context switches"
      }
     ]
    },
    {
     "title": "Interrupts",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
     "repeat": "node",
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(node_intr_total{instance=~\"$host\"}[5m])",
       "legendFormat": "Interrupts",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_running%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    },
    {
     "title": "Processes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
     "repeat": "node",
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "node_procs_running{instance=~\"$node\"}",
       "legendFormat": "Processes in runnable state",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_running%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      },
      {
       "calculatedInterval": "2m",
       "expr": "node_procs_blocked{instance=~\"$node\"}",
       "legendFormat": "Processes blocked waiting for I/O to complete",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_blocked%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    },
    {
     "title": "Forks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 95 },
     "repeat": "node",
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(node_forks_total{instance=~\"$node\"}[5m])",
       "legendFormat": "Forks",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_running%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    }
   ]
  },
  {
   "title": "Hard Drive",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Space Used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "repeat": "node",
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100.0 - 100 * (node_filesystem_avail_bytes{instance=~'$node',device !~'tmpfs',device!~'by-uuid'} / node_filesystem_size_bytes{instance=~'$node',device !~'tmpfs',device!~'by-uuid'})",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk Utilization per Device",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
     "repeat": "node",
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node\"}[5m])*100",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk IOs per Device",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
     "repeat": "node",
     "yaxes": [
      { "format": "short", "label": "IO/second read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{instance=~'$node'}[5m])",
       "legendFormat": "{{device}}_read"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{instance=~'$node'}[5m])",
       "legendFormat": "{{device}}_write"
      }
     ]
    },
    {
     "title": "Disk Throughput per Device",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
     "repeat": "node",
     "yaxes": [
      {
       "format": "Bps",
       "label": "Bytes/second read (-) / write (+)"
      }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=~'$node'}[5m])",
       "legendFormat": "{{device}}_read"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=~'$node'}[5m])",
       "legendFormat": "{{device}}_write"
      }
     ]
    },
    {
     "title": "Disk Queue Length",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 107 },
     "repeat": "node",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_disk_io_now{instance=~\"$node\"}",
       "legendFormat": "{{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Bandwidth",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "repeat": "node",
     "targets": [
      {
       "expr": "sum(increase(node_network_receive_bytes_total{instance=~\"$node\",device=~\"(eth|en|ib|sl|wl|ww).*\"}[$__range]))",
       "legendFormat": "Download"
      },
      {
       "expr": "sum(increase(node_network_transmit_bytes_total{instance=~\"$node\",device=~\"(eth|en|ib|sl|wl|ww).*\"}[$__range]))",
       "legendFormat": "Upload"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "repeat": "node",
     "yaxes": [
      { "format": "Bps", "label": "in (-) / out (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_transmit_bytes_total{instance=~'$node',device=~\"(eth|en|ib|sl|wl|ww).*\"}[5m])",
       "legendFormat": "{{device}}_out"
      },
      {
       "expr": "irate(node_network_receive_bytes_total{instance=~'$node',device=~\"(eth|en|ib|sl|wl|ww).*\"}[5m])",
       "legendFormat": "{{device}}_in"
      }
     ]
    },
    {
     "title": "Netstat",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "repeat": "node",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
       "legendFormat": "established"
      }
     ]
    },
    {
     "title": "UDP Stats",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "repeat": "node",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Udp_InDatagrams{instance=~\"$node\"}[5m])",
       "legendFormat": "Udp_InDatagrams"
      },
      {
       "expr": "irate(node_netstat_Udp_InErrors{instance=~\"$node\"}[5m])",
       "legendFormat": "Udp_InErrors"
      },
      {
       "expr": "irate(node_netstat_Udp_OutDatagrams{instance=~\"$node\"}[5m])",
       "legendFormat": "Udp_OutDatagrams"
      },
      {
       "expr": "irate(node_netstat_Udp_NoPorts{instance=~\"$node\"}[5m])",
       "legendFormat": "Udp_NoPorts"
      }
     ]
    },
    {
     "title": "Conntrack",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
     "repeat": "node",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_nf_conntrack_entries_limit{instance=~\"$node\"} - node_nf_conntrack_entries{instance=~\"$node\"}",
       "legendFormat": "free"
      }
     ]
    }
   ]
  }
 ]
}