---
- name: Set project directory
  ansible.builtin.set_fact:
    _docker_project_dir: "{{ dapp_common_directory }}/{{ role_name }}"

- name: Create project directory
  ansible.builtin.file:
    path: "{{ _docker_project_dir }}"
    state: directory

- name: Copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ _docker_project_dir }}/docker-compose.yml"
    mode: 0640

- name: Copy Dockerfile
  ansible.builtin.copy:
    dest: "{{ _docker_project_dir }}/Dockerfile"
    content: "{{ dapp_trailblazing_dockerfile }}"
  notify: Rebuild containers

- name: Copy local.py
  ansible.builtin.copy:
    content: "{{ dapp_trailblazing_local_py }}"
    dest: "{{ _docker_project_dir }}/local.py"
    mode: 0644
  notify: Restart containers

- name: Copy SAML private.key
  ansible.builtin.copy:
    content: "{{ dapp_trailblazing_saml_private_key }}"
    dest: "{{ _docker_project_dir }}/saml_private.key"
    mode: 0644
  when: dapp_trailblazing_saml_private_key is defined
  notify: Restart containers

- name: Copy SAML public.cert
  ansible.builtin.copy:
    content: "{{ dapp_trailblazing_saml_public_cert }}"
    dest: "{{ _docker_project_dir }}/saml_public.cert"
    mode: 0644
  when: dapp_trailblazing_saml_public_cert is defined
  notify: Restart containers

- name: Copy idp_metadata.xml
  ansible.builtin.copy:
    content: "{{ dapp_trailblazing_idp_metadata_xml }}"
    dest: "{{ _docker_project_dir }}/idp_metadata.xml"
    mode: 0644
  when: dapp_trailblazing_idp_metadata_xml is defined
  notify: Restart containers

- name: Start containers
  ansible.builtin.shell: |
    docker compose --project-directory "{{ _docker_project_dir }}" up -d
  changed_when: false

- name: Flush handlers
  meta: flush_handlers
