---
networks:
  traefik_proxy:
    external: true

services:
  app:
    build: "./"
    image: "localbuild/lustre_exporter_slurm"
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: "lustre_exporter_slurm"
    networks:
      - traefik_proxy
{% if dapp_lustre_exporter_slurm_docker_mem_limit is defined %}
    mem_limit: {{ dapp_lustre_exporter_slurm_docker_mem_limit }}
{% endif %}
    ports:
      {{ dapp_lustre_exporter_slurm_docker_ports|to_nice_yaml|indent(6) }}
    environment:
      {{ dapp_lustre_exporter_slurm_docker_environment|indent(6) }}
    healthcheck:
      {{ dapp_lustre_exporter_slurm_docker_healthcheck|indent(6) }}
    volumes:
      {{ dapp_lustre_exporter_slurm_docker_volumes|to_nice_yaml|indent(6) }}
    labels:
      traefik.enable: "false"
