---
- name: Set project directory
  ansible.builtin.set_fact:
    _docker_project_dir: "{{ dapp_common_directory }}/{{ role_name }}"

- name: Create project directory
  ansible.builtin.file:
    path: "{{ _docker_project_dir }}"
    state: directory

- name: Copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ _docker_project_dir }}/docker-compose.yml"
    mode: 0640
  no_log: true

- name: Copy prometheus.yml
  ansible.builtin.copy:
    content: "{{ dapp_monitoring_prometheus_yml }}"
    dest: "{{ _docker_project_dir }}/prometheus.yml"
    mode: 0644
  notify: Restart containers

- name: Copy prometheus_alerts.yml
  ansible.builtin.copy:
    content: "{{ dapp_monitoring_prometheus_alerts_yml }}"
    dest: "{{ _docker_project_dir }}/prometheus_alerts.yml"
    mode: 0644
  notify: Restart containers

- name: Copy prometheus_recording.yml
  ansible.builtin.copy:
    content: "{{ dapp_monitoring_prometheus_recording_yml }}"
    dest: "{{ _docker_project_dir }}/prometheus_recording.yml"
    mode: 0644
  notify: Restart containers

- name: Copy alertmanager.yml
  ansible.builtin.copy:
    content: "{{ dapp_monitoring_alertmanager_yml }}"
    dest: "{{ _docker_project_dir }}/alertmanager.yml"
    mode: 0644
  notify: Restart containers

- name: Copy blackbox_config.yml
  ansible.builtin.copy:
    content: "{{ dapp_monitoring_blackbox_config_yml }}"
    dest: "{{ _docker_project_dir }}/blackbox_config.yml"
    mode: 0644
  notify: Restart containers

- name: Copy grafana_datasources.yml
  ansible.builtin.copy:
    content: "{{ dapp_monitoring_grafana_datasources_yml }}"
    dest: "{{ _docker_project_dir }}/grafana_datasources.yml"
    mode: 0644
  notify: Restart containers

- name: Copy grafana_providers.yml
  ansible.builtin.copy:
    content: "{{ dapp_monitoring_grafana_providers_yml }}"
    dest: "{{ _docker_project_dir }}/grafana_providers.yml"
    mode: 0644
  notify: Restart containers

- name: Copy grafana_ldap.toml
  ansible.builtin.copy:
    content: "{{ dapp_monitoring_grafana_ldap_toml }}"
    dest: "{{ _docker_project_dir }}/grafana_ldap.toml"
    mode: 0640
  when: dapp_monitoring_grafana_ldap_toml is defined
  no_log: true
  notify: Restart containers

- name: Copy grafana dashboards
  ansible.builtin.copy:
    src: grafana_dashboards/
    dest: "{{ _docker_project_dir }}/grafana_dashboards/ansible"
  notify: Restart containers

- name: Copy grafana.env
  ansible.builtin.copy:
    content: "{{ dapp_monitoring_grafana_env }}"
    dest: "{{ _docker_project_dir }}/grafana.env"
    mode: 0640
  no_log: true
  notify: Restart containers

- name: Copy redfish_config.yml
  ansible.builtin.copy:
    content: "{{ dapp_monitoring_redfish_config_yml }}"
    dest: "{{ _docker_project_dir }}/redfish_config.yml"
    mode: 0644
  no_log: true
  notify: Restart containers
  when: dapp_monitoring_redfish_config_yml is defined

- name: Start containers
  ansible.builtin.shell: |
    docker compose --project-directory "{{ _docker_project_dir }}" up -d
  changed_when: false

- name: Flush handlers
  meta: flush_handlers
