---
volumes:
  mongo:
  opensearch:
  journal:
  webconfig:

networks:
  default:
  traefik_proxy:
    external: true

services:

  mongo:
    image: "{{ graylog_mongo_docker_image }}"
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: "graylog_mongo"
    networks:
      - default
    mem_limit: 512M
    environment:
      TZ: "America/New_York"
      PHP_TZ: "America/New_York"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      {{ graylog_mongo_volumes|to_nice_yaml|indent(6) }}
    labels:
      traefik.enable: "false"

  opensearch:
    image: "{{ graylog_opensearch_docker_image }}"
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: "graylog_opensearch"
    networks:
      - default
    mem_limit: 2048M
    environment:
      TZ: "America/New_York"
      http.host: "0.0.0.0"
      transport.host: "localhost"
      network.host: "0.0.0.0"
      OPENSEARCH_JAVA_OPTS: "-Xms1024m -Xmx1024m -Dlog4j2.formatMsgNoLookups=true"
      discovery.type: "single-node"
      # access opensearch using http
      plugins.security.disabled: "true"
      #reindex.remote.whitelist: "*:9200"
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: "{{ graylog_opensearch_admin_pwd }}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      {{ graylog_opensearch_volumes|to_nice_yaml|indent(6) }}
    labels:
      traefik.enable: "false"

  app:
    image: "{{ graylog_docker_image }}"
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: "graylog_app"
    networks:
      - default
      - traefik_proxy
    mem_limit: 2048M
    environment:
      TZ: "America/New_York"
      PHP_TZ: "America/New_York"
    ports: {{ graylog_ports }}
    expose:
      - "80"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      {{ graylog_volumes|to_nice_yaml|indent(6) }}
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik_proxy"
      traefik.http.routers.graylog.rule: "Host(`{{ graylog_traefik_address }}`)"
{% if common_traefik_tls %}
      traefik.http.routers.graylog.tls: "true"
{% endif %}
{% if common_traefik_tls and common_traefik_certresolver != "none" %}
      traefik.http.routers.graylog.tls.certresolver: "{{ common_traefik_certresolver }}"
      traefik.http.routers.graylog.tls.domains[0].main: "{{ graylog_traefik_address }}"
{% endif %}
    links:
      - "mongo:mongo"
      - "opensearch:opensearch"
