---
volumes:
  mongo:
  opensearch:
  journal:
  webconfig:

networks:
  default:
  traefik_proxy:
    external: true

services:

  mongo:
    image: "{{ dapp_graylog_mongo_docker_image }}"
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: "graylog_mongo"
    networks:
      - default
    mem_limit: {{ dapp_graylog_mongo_docker_mem_limit }}
    environment:
      {{ dapp_graylog_mongo_docker_environment|indent(6) }}
    healthcheck:
      {{ dapp_graylog_mongo_docker_healthcheck|indent(6) }}
    volumes:
      {{ dapp_graylog_mongo_volumes|to_nice_yaml|indent(6) }}
    labels:
      traefik.enable: "false"

  opensearch:
    image: "{{ dapp_graylog_opensearch_docker_image }}"
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: "graylog_opensearch"
    networks:
      - default
    mem_limit: {{ dapp_graylog_opensearch_docker_mem_limit }}
    environment:
      {{ dapp_graylog_opensearch_docker_environment|indent(6) }}
    healthcheck:
      {{ dapp_graylog_opensearch_docker_healthcheck|indent(6) }}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      {{ dapp_graylog_opensearch_volumes|to_nice_yaml|indent(6) }}
    labels:
      traefik.enable: "false"

  app:
    image: "{{ dapp_graylog_docker_image }}"
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: "graylog_app"
    networks:
      - default
      - traefik_proxy
    mem_limit: {{ dapp_graylog_docker_mem_limit }}
    environment:
      {{ dapp_graylog_docker_environment|indent(6) }}
    healthcheck:
      {{ dapp_graylog_docker_healthcheck|indent(6) }}
    ports: {{ dapp_graylog_ports }}
    expose:
      - "80"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      {{ dapp_graylog_volumes|to_nice_yaml|indent(6) }}
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik_proxy"
      traefik.http.routers.graylog.rule: "Host(`{{ dapp_graylog_traefik_address }}`)"
{% if dapp_common_traefik_tls %}
      traefik.http.routers.graylog.tls: "true"
{% endif %}
{% if dapp_common_traefik_tls and dapp_common_traefik_certresolver != "none" %}
      traefik.http.routers.graylog.tls.certresolver: "{{ dapp_common_traefik_certresolver }}"
      traefik.http.routers.graylog.tls.domains[0].main: "{{ dapp_graylog_traefik_address }}"
{% endif %}
    links:
      - "mongo:mongo"
      - "opensearch:opensearch"
