---
- name: Set project directory
  ansible.builtin.set_fact:
    _docker_project_dir: "{{ dapp_common_directory }}/{{ role_name }}"

- name: Create project directory
  ansible.builtin.file:
    path: "{{ _docker_project_dir }}"
    state: directory

- name: Create mirrors directory
  ansible.builtin.file:
    path: "{{ _docker_project_dir }}/mirrors"
    state: directory

- name: Create extras directory
  ansible.builtin.file:
    path: "{{ _docker_project_dir }}/extras"
    state: directory

- name: Create keys directory
  ansible.builtin.file:
    path: "{{ _docker_project_dir }}/keys"
    state: directory

- name: Create container_files directory
  ansible.builtin.file:
    path: "{{ _docker_project_dir }}/container_files"
    state: directory

- name: Copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ _docker_project_dir }}/docker-compose.yml"
    mode: 0640

- name: Copy Dockerfile
  ansible.builtin.copy:
    dest: "{{ _docker_project_dir }}/Dockerfile"
    content: "{{ dapp_mirrordeb_dockerfile }}"
  notify: Rebuild containers

- name: Copy entrypoint.sh
  ansible.builtin.copy:
    dest: "{{ _docker_project_dir }}/entrypoint.sh"
    content: "{{ dapp_mirrordeb_entrypoint }}"
  notify: Rebuild containers

- name: Copy container files
  ansible.builtin.copy:
    dest: "{{ _docker_project_dir }}/container_files/{{ item.name }}"
    content: "{{ item.content }}"
  notify: Rebuild containers
  loop:
    - { name: "run_debmirror.sh", content: "{{ dapp_mirrordeb_script_debmirror }}" }
    - { name: "run_download_installers.sh", content: "{{ dapp_mirrordeb_script_download_installers }}" }
    - { name: "run_download_keys.sh", content: "{{ dapp_mirrordeb_script_download_keys }}" }
    - { name: "run_scanpackages.sh", content: "{{ dapp_mirrordeb_script_dpkg_scanpackages }}" }
    - { name: "nginx.conf", content: "{{ dapp_mirrordeb_nginx_conf }}" }
    - { name: "debmirror.patch", content: "{{ __debmirror_patch }}" }
  loop_control:
    label: "{{ item.name }}"

- name: Start containers
  ansible.builtin.shell: |
    docker compose --project-directory "{{ _docker_project_dir }}" up -d
  changed_when: false

- name: Flush handlers
  meta: flush_handlers
