---
networks:
  traefik_proxy:
    external: true

services:

  app:
    image: "{{ privatebin_docker_image }}"
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: "privatebin"
    networks:
      - traefik_proxy
    mem_limit: 256M
    environment:
      TZ: "America/New_York"
      PHP_TZ: "America/New_York"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik_proxy"
      traefik.http.routers.privatebin.entrypoints: "http, https"
      traefik.http.routers.privatebin.rule: "Host(`{{ privatebin_traefik_address }}`)"
{% if common_traefik_tls %}
      traefik.http.routers.privatebin.tls: "true"
{% endif %}
{% if common_traefik_tls and common_traefik_certresolver != "none" %}
      traefik.http.routers.privatebin.tls.certresolver: "{{ common_traefik_certresolver }}"
      traefik.http.routers.privatebin.tls.domains[0].main: "{{ privatebin_traefik_address }}"
{% endif %}
