---
networks:
  traefik_proxy:
    external: true

services:

  app:
    image: "{{ dapp_privatebin_docker_image }}"
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: "privatebin"
    networks:
      - traefik_proxy
{% if dapp_privatebin_docker_mem_limit is defined %}
    mem_limit: {{ dapp_privatebin_docker_mem_limit }}
{% endif %}
    environment:
      {{ dapp_privatebin_docker_environment|indent(6) }}
    healthcheck:
      {{ dapp_privatebin_docker_healthcheck|indent(6) }}
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik_proxy"
      traefik.http.routers.privatebin.entrypoints: "http, https"
      traefik.http.routers.privatebin.rule: "Host(`{{ dapp_privatebin_traefik_address }}`)"
{% if dapp_common_traefik_tls %}
      traefik.http.routers.privatebin.tls: "true"
{% endif %}
{% if dapp_common_traefik_tls and dapp_common_traefik_certresolver != "none" %}
      traefik.http.routers.privatebin.tls.certresolver: "{{ dapp_common_traefik_certresolver }}"
      traefik.http.routers.privatebin.tls.domains[0].main: "{{ dapp_privatebin_traefik_address }}"
{% endif %}
