  thanos-bucket:
    image: "{{ dapp_thanos_docker_image }}"
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: "thanos-bucket"
    networks:
      - traefik_proxy
    environment:
      {{ dapp_thanos_environment|indent(6) }}
    volumes: {{ dapp_thanos_bucket_volumes }}
    command:
      {{ dapp_thanos_bucket_commande|indent(6) }}
    depends_on:
      - minio
    labels:
      traefik.enable: "false"
      traefik.docker.network: "traefik_proxy"
      traefik.http.routers.thanos-bucket.entrypoints: "http, https"
      traefik.http.routers.thanos-bucket.rule: "Host(`{{ dapp_thanos_bucket_traefik_address }}`)"
      traefik.http.services.thanos-bucket.loadbalancer.server.port: "10904"
{% if dapp_common_traefik_tls %}
      traefik.http.routers.thanos-bucket.tls: "false"
{% endif %}
{% if dapp_common_traefik_tls and dapp_common_traefik_certresolver != "none" %}
      traefik.http.routers.thanos-bucket.tls.certresolver: "{{ dapp_common_traefik_certresolver }}"
{% endif %}
