{% if compactor is defined %}
{{ compactor.name }}-set-volume-owner:
  image: docker.io/alpine
  volumes:
    {{ compactor.volumes | to_nice_yaml | indent(4) }}
  # Set compactor volume owner to 'thanos'
  command: sh -c "chown 1001:1001 /data || exit 1"
  user: "root"
  restart: "no"

{{ compactor.name }}:
  image: "{{ dapp_thanos_docker_image }}"
  container_name: {{ compactor.name }}
  restart: unless-stopped
  logging:
    driver: journald
    options:
      tag: "{{ compactor.name }}"
  networks:
    - traefik_proxy
  environment:
    {{ dapp_thanos_environment | indent(6) }}
  volumes:
    {{ compactor.volumes | to_nice_yaml | indent(4) }}
  command:
    {{ compactor.command | to_nice_yaml | indent(4) }}
  depends_on:
    {{ compactor.name }}-set-volume-owner:
      condition: service_completed_successfully
  labels:
    traefik.enable: "false"
{% endif %}
