  thanos-query-frontend:
    image: "{{ dapp_thanos_docker_image }}"
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: "thanos-query-frontend"
    networks:
      - traefik_proxy
    environment:
      {{ dapp_thanos_environment|indent(6) }}
    volumes: {{ dapp_thanos_queryfrontend_volumes }}
    command:
      {{ dapp_thanos_queryfrontend_commande|indent(6) }}
    depends_on:
      - thanos-querier
    labels:
      traefik.enable: "false"
      traefik.docker.network: "traefik_proxy"
      traefik.http.routers.thanos-queryfrontend.entrypoints: "http, https"
      traefik.http.routers.thanos-queryfrontend.rule: "Host(`{{ dapp_thanos_queryfrontend_traefik_address }}`)"
      traefik.http.services.thanos-queryfrontend.loadbalancer.server.port: "10901"
{% if dapp_common_traefik_tls %}
      traefik.http.routers.thanos-queryfrontend.tls: "false"
{% endif %}
{% if dapp_common_traefik_tls and dapp_common_traefik_certresolver != "none" %}
      traefik.http.routers.thanos-queryfrontend.tls.certresolver: "{{ dapp_common_traefik_certresolver }}"
{% endif %}
