{% if sidecar is defined %}
{{ sidecar.name }}:
  image: "{{ dapp_thanos_docker_image }}"
  container_name: {{ sidecar.name }}
  restart: unless-stopped
  logging:
    driver: journald
    options:
      tag: "{{ sidecar.name }}"
  networks:
    - traefik_proxy
  expose: {{ sidecar.expose }}
{% if sidecar.user is defined %}
  user: {{ sidecar.user }}
{% endif %}
  environment:
    {{ dapp_thanos_environment|indent(6) }}
  volumes: {{ sidecar.volumes }}
  command: {{ sidecar.command }}
  labels:
    traefik.enable: "false"
{% endif %}
