{% if sc is defined %}
{{ sc.name }}:
  image: "{{ dapp_thanos_docker_image }}"
  restart: unless-stopped
  logging:
    driver: journald
    options:
      tag: "thanos-sidecar"
  networks:
    - traefik_proxy
  environment:
    {{ sc.dapp_thanos_environment|indent(6) }}
  volumes: {{ sc.dapp_thanos_sidecar_volumes }}
  command:
    {{ sc.dapp_thanos_sidecar_commande|indent(6) }}
  depends_on:
    - prometheus-4
    - minio
  labels:
    traefik.enable: "false"
{% endif %}
