thanos-store-gateway:
  image: "{{ dapp_thanos_docker_image }}"
  restart: unless-stopped
  logging:
    driver: journald
    options:
      tag: "thanos-store-gateway"
  networks:
    - traefik_proxy
  environment:
    {{ dapp_thanos_environment|indent(6) }}
  volumes: {{ dapp_thanos_store_gateway_volumes }}
  command:
    {{ dapp_thanos_store_gateway_commande|indent(6) }}
  depends_on:
    - minio
  labels:
    traefik.enable: "false"
    traefik.docker.network: "traefik_proxy"
    traefik.http.routers.thanos-store-gateway.entrypoints: "http, https"
    traefik.http.routers.thanos-store-gateway.rule: "Host(`{{ dapp_thanos_store_gateway_traefik_address }}`)"
    traefik.http.services.thanos-store-gateway.loadbalancer.server.port: "10902"
{% if dapp_common_traefik_tls %}
    traefik.http.routers.thanos-store-gateway.tls: "false"
{% endif %}
{% if dapp_common_traefik_tls and dapp_common_traefik_certresolver != "none" %}
    traefik.http.routers.thanos-store-gateway.tls.certresolver: "{{ dapp_common_traefik_certresolver }}"
{% endif %}
