---
# docker image
docker_apps_image_mirror_deb: "localbuild/mirror_deb"

# service address
traefik_address_mirror_deb: "mirror.{{ docker_apps_domain }}"

# debmirror command arguments. FIXME remove --dry-run when all is set
mirror_deb_command_args: --nosource --i18n --passive --cleanup --verbose --dry-run

# Dockerfile to build the container
mirror_deb_dockerfile: |
  FROM debian:stable-slim
  COPY entrypoint.sh /entrypoint.sh
  RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    apt-get install -y --no-install-recommends debmirror ed gnupg gpgv curl nginx dpkg-dev && \
    apt-get -y upgrade && \
    apt-get autoremove && \
    rm -rf /var/cache/apt/* && \
    rm -f /var/www/html/index.nginx-debian.html && \
    chmod u+x /entrypoint.sh
  COPY nginx.conf /etc/nginx/sites-enabled/default
  EXPOSE 80
  ENTRYPOINT ["/entrypoint.sh"]

# entrypoint.sh file for the container
mirror_deb_entrypoint: |
  #!/bin/bash
  # start nginx
  nginx

  # install/update debian keys from https://ftp-master.debian.org/keys.html
  touch /root/.gnupg/trustedkeys.gpg
  chmod 0600 /root/.gnupg/trustedkeys.gpg
  curl https://ftp-master.debian.org/keys/archive-key-11.asc | gpg --no-default-keyring --keyring trustedkeys.gpg --import -
  curl https://ftp-master.debian.org/keys/archive-key-11-security.asc | gpg --no-default-keyring --keyring trustedkeys.gpg --import -
  curl https://ftp-master.debian.org/keys/archive-key-12.asc | gpg --no-default-keyring --keyring trustedkeys.gpg --import -
  curl https://ftp-master.debian.org/keys/archive-key-12-security.asc | gpg --no-default-keyring --keyring trustedkeys.gpg --import -
  curl https://ftp-master.debian.org/keys/release-11.asc | gpg --no-default-keyring --keyring trustedkeys.gpg --import -
  curl https://ftp-master.debian.org/keys/release-12.asc | gpg --no-default-keyring --keyring trustedkeys.gpg --import -

  # Refresh mirror every 6 hours
  while true; do
    logger "scan local packages"
    cd /var/www/html/extras/ && dpkg-scanpackages -m . > Packages && cat Packages | gzip > Packages.gz

    # debian mirror
    # source host
    HOST=debian.mirror.rafal.ca
    # destination directory
    DEST=/var/www/html/mirrors/debian/
    # version(s) to mirror
    DIST=bookworm
    # architecture
    ARCH=amd64
    # http, ftp or rsync
    METHOD=rsync
    # debmirror command
    logger "debmirror updating ${DEST}"
    debmirror {{ mirror_deb_command_args }} \
      --method=${METHOD} --host=${HOST} --root=/debian --dist=${DIST} --arch=${ARCH} \
      --section=main,contrib,non-free,main/debian-installer \
      ${DEST}

    # debian-security mirror
    # source host
    HOST=debian.mirror.rafal.ca
    # destination directory
    DEST=/var/www/html/mirrors/debian-security/
    # version(s) to mirror
    DIST=bookworm
    # architecture
    ARCH=amd64
    # http, ftp or rsync
    METHOD=rsync
    # debmirror command, FIXME remove --dry-run when all is set
    logger "debmirror updating ${DEST}"
    debmirror {{ mirror_deb_command_args }} \
      --method=${METHOD} --host=${HOST} --root=/debian --dist=${DIST} --arch=${ARCH} \
      --section=main,contrib,non-free,main/debian-installer \
      ${DEST}

    logger "debmirror going to sleep"
    sleep 6h
  done

mirror_deb_nginx_conf: |
  server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    server_name _;
    location / {
      autoindex on;
      try_files $uri $uri/ =404;
    }
    access_log syslog:server=unix:/dev/log;
    error_log syslog:server=unix:/dev/log;
  }
