---
- name: Set project directory
  ansible.builtin.set_fact:
    _docker_project_dir: "{{ dapp_common_directory }}/{{ role_name }}"

- name: Create project directory
  ansible.builtin.file:
    path: "{{ _docker_project_dir }}"
    state: directory

- name: Copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ _docker_project_dir }}/docker-compose.yml"
    mode: 0640
  no_log: true

- name: Copy config.ini
  ansible.builtin.copy:
    content: "{{ dapp_lustre_exporter_slurm_config_ini }}"
    dest: "{{ _docker_project_dir }}/config.ini"
    mode: 0640
  no_log: true
  notify: Restart containers

- name: Copy Dockerfile
  copy:
    dest: "{{ _docker_project_dir }}/Dockerfile"
    content: "{{ dapp_lustre_exporter_slurm_dockerfile }}"
    mode: 0640
  notify: Rebuild containers

- name: Copy entrypoint.sh
  copy:
    dest: "{{ _docker_project_dir }}/entrypoint.sh"
    content: "{{ dapp_lustre_exporter_slurm_entrypoint }}"
    mode: 0640
  notify: Rebuild containers

- name: Start containers
  ansible.builtin.shell: |
    docker compose --project-directory "{{ _docker_project_dir }}" up -d
  changed_when: false

- name: Flush handlers
  meta: flush_handlers
