---
- name: Set project directory
  ansible.builtin.set_fact:
    docker_apps_project: "{{ docker_apps_directory }}/{{ role_name }}"

- name: Create project directory
  ansible.builtin.file:
    path: "{{ docker_apps_project }}"
    state: directory

- name: Copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ docker_apps_project }}/docker-compose.yml"
    mode: 0640

- name: Start containers
  ansible.builtin.shell: |
    docker compose --project-directory "{{ docker_apps_project }}" up -d
  changed_when: false
