---
# docker image
dapp_homepage_docker_image: "ghcr.io/gethomepage/homepage"

# homepage server address
dapp_homepage_traefik_address: "www.{{ dapp_common_domain }}"

# The homepage documentation is available at https://gethomepage.dev/.
# icons from https://github.com/walkxcode/dashboard-icons

# homepage settings.yaml file
dapp_homepage_settings_yaml: |
  ---
  title: My Awesome Homepage

# homepage bookmarks.yaml file
dapp_homepage_bookmarks_yaml: |
  ---
  - Developer:
      - Github:
          - abbr: GH
            href: https://github.com/

  - Social:
      - Reddit:
          - icon: reddit.png
            href: https://reddit.com/
            description: The front page of the internet

  - Entertainment:
      - YouTube:
          - abbr: YT
            href: https://youtube.com/

# homepage service.yaml file
dapp_homepage_services_yaml: |
  ---
  - Group A:
      - Service A:
          href: http://localhost/

  - Group B:
      - Service B:
          href: http://localhost/

# homepage widgets.yaml file
dapp_homepage_widgets_yaml: |
  ---
