---
dapp_cpco_exporter_dockerfile: |
  FROM debian:stable-slim
  COPY entrypoint.sh /entrypoint.sh
  RUN DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get update && \
    /usr/bin/apt-get upgrade -y && \
    /usr/bin/apt-get dist-upgrade -ufy && \
    /usr/bin/apt-get install git python3 python3-requests python3-prometheus-client -y && \
    /usr/bin/rm -rf /var/lib/apt/lists/*
  RUN /usr/bin/chmod u+x /entrypoint.sh
  EXPOSE 9340/tcp
  ENTRYPOINT ["/entrypoint.sh"]

dapp_cpco_exporter_entrypoint: |
  #!/bin/bash
  /usr/bin/python3 /exporter.py --modbus-port 502 --listen-port 9340 --listen-host 0.0.0.0 --timeout 10

# docker environment variables
dapp_cpco_exporter_docker_environment: |
  {{ dapp_common_docker_environment }}

# docker healthcheck variables
dapp_cpco_exporter_docker_healthcheck: |
  {{ dapp_common_docker_healthcheck }}

# dapp_cpco_exporter_docker_mem_limit: 512M

dapp_cpco_exporter_docker_ports:
  - "9340:9340"

dapp_cpco_exporter_docker_volumes:
  - "./exporter.py:/exporter.py"
