---
- name: Set project directory
  ansible.builtin.set_fact:
    docker_project_dir: "{{ common_apps_directory }}/{{ role_name }}"

- name: Create project directory
  ansible.builtin.file:
    path: "{{ docker_project_dir }}"
    state: directory

- name: Copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ docker_project_dir }}/docker-compose.yml"
    mode: 0640

- name: Create docker environment file
  ansible.builtin.copy:
    dest: "{{ docker_project_dir }}/traefik.env"
    content: "{{ traefik_env_file }}"
    mode: 0640
  notify: Restart containers

- name: Create traefik serverTransports file
  ansible.builtin.copy:
    dest: "{{ docker_project_dir }}/serversTransports.yml"
    content: "{{ common_traefik_serversTransports }}"
  when: common_traefik_serversTransports is defined
  notify: Restart containers

- name: Import certificate.yml
  ansible.builtin.import_tasks: certificate.yml
  when:
    - common_traefik_tls
    - common_traefik_certresolver == "none"
  notify: Restart containers

- name: Start containers
  ansible.builtin.shell: |
    docker compose --project-directory "{{ docker_project_dir }}" up -d
  changed_when: false
