---
networks:
  traefik_proxy:
    external: true

volumes:
  config:
  logs:
  data:
  runner:
  registry:

services:
  app:
    image: "{{ dapp_gitlab_docker_image }}"
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: "gitlab"
    networks:
      - traefik_proxy
    ports: {{ dapp_gitlab_ports }}
    cpus: {{ dapp_gitlab_cpus }}
    mem_limit: {{ dapp_gitlab_mem_limit }}
    environment:
      {{ dapp_gitlab_docker_environment|indent(6) }}
    healthcheck:
      {{ dapp_gitlab_docker_healthcheck|indent(6) }}
    volumes:
      - "config:/etc/gitlab"
      - "logs:/var/log/gitlab"
      - "data:/var/opt/gitlab"
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik_proxy"
      traefik.http.routers.gitlab.entrypoints: "http, https"
      traefik.http.routers.gitlab.rule: "Host(`{{ dapp_gitlab_traefik_address }}`)"
      traefik.http.services.gitlab.loadbalancer.server.port: "80"
{% if dapp_common_traefik_tls %}
      traefik.http.routers.gitlab.tls: "true"
{% endif %}
{% if dapp_common_traefik_tls and dapp_common_traefik_certresolver != "none" %}
      traefik.http.routers.gitlab.tls.certresolver: "{{ dapp_common_traefik_certresolver }}"
      traefik.http.routers.gitlab.tls.domains[0].main: "{{ dapp_gitlab_traefik_address }}"
{% endif %}

{% if dapp_gitlab_runner_dockerfile is defined %}
  runner:
    image: "{{ dapp_gitlab_runner_docker_image }}"
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: "gitlab-runner"
    cpus: {{ dapp_gitlab_runner_cpus }}
    mem_limit: {{ dapp_gitlab_runner_mem_limit }}
    environment:
      {{ dapp_gitlab_runner_docker_environment|indent(6) }}
    healthcheck:
      {{ dapp_gitlab_runner_docker_healthcheck|indent(6) }}
    volumes:
      - "runner:/etc/gitlab-runner"
      - "/run/user/{{ docker_rootless_user.uid }}/docker.sock:/var/run/docker.sock"
    labels:
      traefik.enable: "false"
{% endif %}
