---
networks:
  traefik_proxy:
    external: true

volumes:
  config:
  logs:
  data:
  runner:
  registry:

services:
  app:
    image: "{{ gitlab_docker_image }}"
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: "gitlab"
    networks:
      - traefik_proxy
    ports: {{ gitlab_ports }}
    cpus: {{ gitlab_cpus }}
    mem_limit: {{ gitlab_mem_limit }}
    environment:
      TZ: "America/New_York"
      GITLAB_OMNIBUS_CONFIG: |
        {{ gitlab_omnibus_config|indent(8) }}
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "config:/etc/gitlab"
      - "logs:/var/log/gitlab"
      - "data:/var/opt/gitlab"
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik_proxy"
      traefik.http.routers.gitlab.entrypoints: "http, https"
      traefik.http.routers.gitlab.rule: "Host(`{{ gitlab_traefik_address }}`)"
      traefik.http.services.gitlab.loadbalancer.server.port: "80"
{% if common_traefik_tls %}
      traefik.http.routers.gitlab.tls: "true"
{% endif %}
{% if common_traefik_tls and common_traefik_certresolver != "none" %}
      traefik.http.routers.gitlab.tls.certresolver: "{{ common_traefik_certresolver }}"
      traefik.http.routers.gitlab.tls.domains[0].main: "{{ gitlab_traefik_address }}"
{% endif %}

  runner:
    image: "{{ gitlab_runner_docker_image }}"
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: "gitlab-runner"
    cpus: {{ gitlab_runner_cpus }}
    mem_limit: {{ gitlab_runner_mem_limit }}
    environment:
      TZ: "America/New_York"
    volumes:
      - "runner:/etc/gitlab-runner"
      - "/run/user/{{ docker_rootless_user.uid }}/docker.sock:/var/run/docker.sock"
    labels:
      traefik.enable: "false"
