---
# docker image
mirrordeb_docker_image: "localbuild/mirrordeb"

# service address
mirrordeb_traefik_address: "mirror.{{ common_apps_domain }}"

# About 'mirrordeb_directory_*', you can change them,
# but you have to create the directories yourself; this role won't do it.

# main directory for debmirror destination
mirrordeb_directory_mirrors: "./mirrors"

# directory for 'extras' packages
mirrordeb_directory_extras: "./extras"

# directory for key files
mirrordeb_directory_keys: "./keys"

# mirror settings (remove '--dry-run' option when all is set)
mirrordeb_mirrors:
  - name: debian
    host: debian.mirror.rafal.ca
    root: /debian
    dist: bookworm,bookworm-updates
    arch: amd64
    section: main,contrib,non-free,non-free-firmware,main/debian-installer
    dest: /var/www/html/mirrors/debian/
    method: rsync
    options: --nosource --i18n --passive --cleanup --verbose --dry-run
  - name: debian-security
    host: debian.mirror.rafal.ca
    root: /debian-security
    dist: bookworm-security
    arch: amd64
    section: main,contrib,non-free,non-free-firmware,main/debian-installer
    dest: /var/www/html/mirrors/debian-security/
    method: rsync
    options: --nosource --i18n --passive --cleanup --verbose --dry-run
  - name: ubuntu
    host: ca.archive.ubuntu.com
    root: /ubuntu
    dist: jammy,jammy-security
    arch: amd64
    section: main,restricted,universe,multiverse
    dest: /var/www/html/mirrors/ubuntu/
    method: rsync
    options: --nosource --i18n --passive --cleanup --verbose --dry-run

# signing keys
mirrordeb_signing_keys:
  - https://ftp-master.debian.org/keys/archive-key-11.asc
  - https://ftp-master.debian.org/keys/archive-key-11-security.asc
  - https://ftp-master.debian.org/keys/archive-key-12.asc
  - https://ftp-master.debian.org/keys/archive-key-12-security.asc
  - https://ftp-master.debian.org/keys/release-11.asc
  - https://ftp-master.debian.org/keys/release-12.asc
  - https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x630239cc130e1a7fd81a27b140976eaf437d05b5 # Ubuntu Archive Automatic Signing Key
  - https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xf6ecb3762474eda9d21b7022871920d1991bc93c # Ubuntu Archive Automatic Signing Key(2018)

# Dockerfile to build the container
mirrordeb_dockerfile: |
  FROM debian:stable-slim
  RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    apt-get install -y --no-install-recommends debmirror ed gnupg gpgv curl nginx dpkg-dev && \
    apt-get -y upgrade && \
    apt-get autoremove && \
    rm -rf /var/cache/apt/*
  COPY entrypoint.sh /entrypoint.sh
  RUN chmod u+x /entrypoint.sh && \
    rm -f /var/www/html/index.nginx-debian.html
  COPY nginx.conf /etc/nginx/sites-enabled/default
  EXPOSE 80
  ENTRYPOINT ["/entrypoint.sh"]

# container entrypoint.sh
mirrordeb_entrypoint: |
  #!/bin/bash
  echo "start nginx ..."
  nginx

  # install/update signing keys
  echo "update signing keys ..."
  touch /root/.gnupg/trustedkeys.gpg
  chmod 0600 /root/.gnupg/trustedkeys.gpg
  {% for akey in mirrordeb_signing_keys %}
  curl '{{ akey }}' | gpg --no-default-keyring --keyring trustedkeys.gpg --import -
  {% endfor %}

  # Refresh mirror every 6 hours
  while true; do
    echo "scan local packages ..."
    cd /var/www/html/extras/ && dpkg-scanpackages -m . > Packages && cat Packages | gzip > Packages.gz

  {% for amirror in mirrordeb_mirrors %}
    echo "debmirror {{ amirror.name }} ..."
    debmirror {{ amirror.options }} \
      --method={{ amirror.method }} --host={{ amirror.host }} --root={{ amirror.root }} \
      --dist={{ amirror.dist }} --arch={{ amirror.arch }} \
      --section={{ amirror.section }} {{ amirror.dest }}

  {% endfor %}

    echo "going to sleep ..."
    sleep 6h
  done

# nging configuration file
mirrordeb_nginx_conf: |
  server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    server_name _;
    location / {
      autoindex on;
      try_files $uri $uri/ =404;
    }
    access_log syslog:server=unix:/dev/log;
    error_log syslog:server=unix:/dev/log;
  }
