---
# docker image
# Check version compatibility between graylog, mongo and opensearch, before updating.
# https://go2docs.graylog.org/current/upgrading_graylog/upgrading_graylog_in_docker.htm
dapp_graylog_docker_image: "docker.io/graylog/graylog:6.1.10"
dapp_graylog_mongo_docker_image: "docker.io/mongo:6.0.14"
dapp_graylog_opensearch_docker_image: "docker.io/opensearchproject/opensearch:2.15.0"

# graylog docker environment variables
dapp_graylog_docker_environment: |
  {{ dapp_common_docker_environment }}

# mongo docker environment variables
dapp_graylog_mongo_docker_environment: |
  {{ dapp_common_docker_environment }}

# opensearch docker environment variables
dapp_graylog_opensearch_docker_environment: |
  {{ dapp_common_docker_environment }}
  http.host: "0.0.0.0"
  transport.host: "localhost"
  network.host: "0.0.0.0"
  OPENSEARCH_JAVA_OPTS: "-Xms1024m -Xmx1024m -Dlog4j2.formatMsgNoLookups=true"
  discovery.type: "single-node"
  # access opensearch using http
  plugins.security.disabled: "true"
  #reindex.remote.whitelist: "*:9200"
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: "{{ dapp_graylog_opensearch_admin_pwd }}"

# graylog docker healthcheck variables
dapp_graylog_docker_healthcheck: |
  {{ dapp_common_docker_healthcheck }}

# mongo docker healthcheck variables
dapp_graylog_mongo_docker_healthcheck: |
  {{ dapp_common_docker_healthcheck }}

# opensearch docker healthcheck variables
dapp_graylog_opensearch_docker_healthcheck: |
  {{ dapp_common_docker_healthcheck }}

# Docker mem_limit
# dapp_graylog_mongo_docker_mem_limit: 512M
# dapp_graylog_opensearch_docker_mem_limit: 2048M
# dapp_graylog_docker_mem_limit: 2048M

# graylog server address
dapp_graylog_traefik_address: "graylog.{{ dapp_common_domain }}"

# graylog listening ports
dapp_graylog_ports:
  - "514:514/tcp" # syslog
  - "514:514/udp" # syslog
  - "5555:5555"   # raw4json

# admin password hash as sha256sum.
# echo -n "Enter Password: " && head -1 </dev/stdin | tr -d '\n' | sha256sum | cut -d" " -f1
# dapp_graylog_root_password_sha2: <secret>

# a secret that is used for password encryption and salting.
# dapp_graylog_password_secret: <secret>

# opensearch admin password
# dapp_graylog_opensearch_admin_pwd: <secret>

dapp_graylog_volumes:
  - "./graylog.conf:/usr/share/graylog/data/config/graylog.conf"
  - "journal:/usr/share/graylog/data/journal"
  - "webconfig:/usr/share/graylog/data/config"

dapp_graylog_mongo_volumes:
  - "mongo:/data/db"

dapp_graylog_opensearch_volumes:
  - "opensearch:/usr/share/opensearch/data"

# These properties configure email notification delivery settings.
# dapp_graylog_smtp_mailfrom: "graylog@{{ dapp_common_domain }}"
# dapp_graylog_smtp_server: "mail.{{ dapp_common_domain }}"
# dapp_graylog_smtp_port: 25
# dapp_graylog_smtp_enabled: false
# dapp_graylog_smtp_auth_username: nobody
# dapp_graylog_smtp_auth_password: secret
# dapp_graylog_smtp_use_auth: false
# dapp_graylog_smtp_use_ssl: false
# dapp_graylog_smtp_use_tls: false

# graylog.conf file
dapp_graylog_conf_file: |
  allow_highlighting = false
  allow_leading_wildcard_searches = false
  bin_dir = /usr/share/graylog/bin
  data_dir = /usr/share/graylog/data
  elasticsearch_analyzer = standard
  elasticsearch_hosts = http://admin:{{ dapp_graylog_opensearch_admin_pwd }}@opensearch:9200
  elasticsearch_index_prefix = graylog
  elasticsearch_max_docs_per_index = 20000000
  elasticsearch_max_number_of_indices = 20
  elasticsearch_replicas = 0
  elasticsearch_shards = 4
  http_bind_address = 0.0.0.0:80
  http_external_uri = https://{{ dapp_graylog_traefik_address }}/
  http_publish_uri = http://localhost/
  is_master = true
  lb_recognition_period_seconds = 3
  message_journal_dir = data/journal
  message_journal_enabled = true
  mongodb_max_connections = 1000
  mongodb_threads_allowed_to_block_multiplier = 5
  mongodb_uri = mongodb://mongo/graylog
  node_id_file = /usr/share/graylog/data/config/node-id
  password_secret = {{ dapp_graylog_password_secret }}
  plugin_dir = /usr/share/graylog/plugin
  retention_strategy = delete
  root_password_sha2 = {{ dapp_graylog_root_password_sha2 }}
  root_timezone = Canada/Eastern
  root_username = admin
  rotation_strategy = count
  transport_email_auth_password = {{ dapp_graylog_smtp_auth_password | default('') }}
  transport_email_auth_username = {{ dapp_graylog_smtp_auth_username | default('') }}
  transport_email_enabled = {{ dapp_graylog_smtp_enabled | default(false) }}
  transport_email_from_email = {{ dapp_graylog_smtp_mailfrom | default('') }}
  transport_email_hostname = {{ dapp_graylog_smtp_server | default('') }}
  transport_email_port = {{ dapp_graylog_smtp_port | default(25) }}
  transport_email_subject_prefix = [GRAYLOG]
  transport_email_use_auth = {{ dapp_graylog_smtp_use_auth | default(false) }}
  transport_email_use_ssl = {{ dapp_graylog_smtp_use_ssl | default(false) }}
  transport_email_use_tls = {{ dapp_graylog_smtp_use_tls | default(false) }}
  transport_email_web_interface_url = https://{{ dapp_graylog_traefik_address }}
  # Performance problems ?
  # inputbuffer_processors = 1
  # inputbuffer_ring_size = 16384
  # inputbuffer_wait_strategy = sleeping
  # output_batch_size = 2000
  # output_fault_count_threshold = 5
  # output_fault_penalty_seconds = 30
  # output_flush_interval = 1
  # outputbuffer_processors = 1
  # processbuffer_processors = 2
  # processor_wait_strategy = sleeping
  # ring_size = 16384
  # server_java_opts = -Xms1024m -Xmx1024m
