---
- name: "Check required cgroup v1 (failed? set docker_rootless_cgroupv2: false, run docker_rootless_mode & reboot)"
  ansible.builtin.shell: fgrep cgroup_hierarchy=0 /proc/cmdline
  changed_when: false

- name: Set project directory
  ansible.builtin.set_fact:
    docker_project_dir: "{{ common_apps_directory }}/{{ role_name }}"

- name: Create project directory
  ansible.builtin.file:
    path: "{{ docker_project_dir }}"
    state: directory

- name: Copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ docker_project_dir }}/docker-compose.yml"
    mode: 0640

- name: Start containers
  ansible.builtin.shell: |
    docker compose --project-directory "{{ docker_project_dir }}" up -d
  changed_when: false

- name: Fix freeipa http on master server
  ansible.builtin.import_tasks: fixhttp.yml
  when: freeipa_role == "master"

- name: Fix freeipa http on replica servers
  ansible.builtin.import_tasks: fixhttp.yml
  when: freeipa_role == "replica"

- name: Set replication between servers
  ansible.builtin.import_tasks: topologysegment.yml
  when:
    - freeipa_server_replica1 is defined
    - freeipa_server_replica2 is defined
    - freeipa_role == "master"
