---
- name: Set project directory
  ansible.builtin.set_fact:
    _docker_project_dir: "{{ dapp_common_directory }}/{{ role_name }}"

- name: Create project directory
  ansible.builtin.file:
    path: "{{ _docker_project_dir }}"
    state: directory

- name: Copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ _docker_project_dir }}/docker-compose.yml"
    mode: 0640

# certificate.yml not tested
# - name: Manage own certificate
#   ansible.builtin.import_tasks: certificate.yml
#   when: dapp_freeipa_cert is defined

- name: Start containers
  ansible.builtin.shell: |
    docker compose --project-directory "{{ _docker_project_dir }}" up -d
  changed_when: false

- name: Flush handlers
  meta: flush_handlers

- name: Patch freeipa for traefik on master server
  ansible.builtin.import_tasks: fixhttp.yml
  when:
    - dapp_freeipa_role == "master"
    - dapp_freeipa_traefik

- name: Patch freeipa for traefik on replica servers
  ansible.builtin.import_tasks: fixhttp.yml
  when:
    - dapp_freeipa_role == "replica"
    - dapp_freeipa_traefik

- name: Set replication between servers
  ansible.builtin.import_tasks: topologysegment.yml
  run_once: true
  when:
    - dapp_freeipa_server_replica1 is defined
    - dapp_freeipa_server_replica2 is defined
