---
- name: Kinit admin
  ansible.builtin.expect:
    echo: false
    command: docker exec -it freeipa-app-1 /usr/bin/kinit admin
    responses:
      (.*)assword for (.*): "{{ freeipa_pwd_admin }}"
  register: _kinit
  changed_when: false
  no_log: true

- name: Check current domain topology
  ansible.builtin.command: |
    docker exec -t freeipa-app-1 /usr/bin/ipa topologysegment-find domain {{ freeipa_server_replica1 }}-to-{{ freeipa_server_replica2 }}
  register: _topocheckdomain
  ignore_errors: true
  changed_when: false
  no_log: true

- name: Create domain topology between replicas
  ansible.builtin.command: |
    docker exec -t freeipa-app-1 /usr/bin/ipa topologysegment-add domain {{ freeipa_server_replica1 }}-to-{{ freeipa_server_replica2 }} --leftnode={{ freeipa_server_replica1 }} --rightnode={{ freeipa_server_replica2 }}
  when: _topocheckdomain.rc != 0
  changed_when: false
  no_log: true

- name: Check current ca topology
  ansible.builtin.command: |
    docker exec -t freeipa-app-1 /usr/bin/ipa topologysegment-find ca {{ freeipa_server_replica1 }}-to-{{ freeipa_server_replica2 }}
  register: _topocheckca
  ignore_errors: true
  changed_when: false
  no_log: true

- name: Create ca topology between replicas
  ansible.builtin.command: |
    docker exec -t freeipa-app-1 /usr/bin/ipa topologysegment-add ca {{ freeipa_server_replica1 }}-to-{{ freeipa_server_replica2 }} --leftnode={{ freeipa_server_replica1 }} --rightnode={{ freeipa_server_replica2 }}
  when: _topocheckca.rc != 0
  changed_when: false
  no_log: true
