---
networks:
  traefik_proxy:
    external: true

volumes:
  cache:

services:

  app:
    image: "{{ dapp_trivy_docker_image }}"
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: "trivy"
    networks:
      - traefik_proxy
    expose:
      - 80
    mem_limit: 512M
    environment:
      {{ dapp_trivy_docker_environment|indent(6) }}
    healthcheck:
      {{ dapp_trivy_docker_healthcheck|indent(6) }}
    volumes:
      - "cache:/root/.cache/trivy"
    command: server --listen 0.0.0.0:80 --token "{{ dapp_trivy_token }}"
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik_proxy"
      traefik.http.routers.trivy.entrypoints: "http, https"
      traefik.http.routers.trivy.rule: "Host(`{{ dapp_trivy_traefik_address }}`)"
{% if dapp_common_traefik_tls %}
      traefik.http.routers.trivy.tls: "true"
{% endif %}
{% if dapp_common_traefik_tls and dapp_common_traefik_certresolver != "none" %}
      traefik.http.routers.trivy.tls.certresolver: "{{ dapp_common_traefik_certresolver }}"
      traefik.http.routers.trivy.tls.domains[0].main: "{{ dapp_trivy_traefik_address }}"
{% endif %}
