---
volumes:
  alertmanager:
  grafana_plugins:
  prometheus:
  grafana_dashboards:

networks:
  default:
  traefik_proxy:
    external: true

services:

  prometheus:
    image: "{{ monitoring_prometheus_docker_image }}"
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: "prometheus"
    networks:
      - default
      - traefik_proxy
    mem_limit: 512M
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./prometheus_alerts.yml:/etc/prometheus/alerts.yml"
      - "prometheus:/prometheus"
    environment:
      TZ: "America/New_York"
      PHP_TZ: "America/New_York"
    links:
      - alertmanager
      - blackbox
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik_proxy"
      traefik.http.routers.prometheus.rule: "Host(`{{ monitoring_prometheus_traefik_address }}`)"
      traefik.http.services.prometheus.loadbalancer.server.port: "9090"
{% if common_traefik_tls %}
      traefik.http.routers.prometheus.tls: "true"
{% endif %}
{% if common_traefik_tls and common_traefik_certresolver != "none" %}
      traefik.http.routers.prometheus.tls.certresolver: "{{ common_traefik_certresolver }}"
      traefik.http.routers.prometheus.tls.domains[0].main: "{{ monitoring_prometheus_traefik_address }}"
{% endif %}
    command: --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles --storage.tsdb.retention.time={{ monitoring_prometheus_retention_time }}

  alertmanager:
    image: "{{ monitoring_alertmanager_docker_image }}"
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: "alertmanager"
    networks:
      - default
      - traefik_proxy
    mem_limit: 512M
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./alertmanager.yml:/etc/alertmanager/alertmanager.yml"
      - "alertmanager:/alertmanager"
    environment:
      TZ: "America/New_York"
      PHP_TZ: "America/New_York"
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik_proxy"
      traefik.http.routers.alertmanager.rule: "Host(`{{ monitoring_alertmanager_traefik_address }}`)"
      traefik.http.services.alertmanager.loadbalancer.server.port: "9093"
{% if common_traefik_tls %}
      traefik.http.routers.alertmanager.tls: "true"
{% endif %}
{% if common_traefik_tls and common_traefik_certresolver != "none" %}
      traefik.http.routers.alertmanager.tls.certresolver: "{{ common_traefik_certresolver }}"
      traefik.http.routers.alertmanager.tls.domains[0].main: "{{ monitoring_alertmanager_traefik_address }}"
{% endif %}

  blackbox:
    image: "{{ monitoring_blackbox_docker_image }}"
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: "blackbox"
    networks:
      - default
      - traefik_proxy
    mem_limit: 512M
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./blackbox_config.yml:/etc/blackbox_exporter/config.yml"
    environment:
      TZ: "America/New_York"
      PHP_TZ: "America/New_York"
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik_proxy"
      traefik.http.routers.blackbox.rule: "Host(`{{ monitoring_blackbox_traefik_address }}`)"
      traefik.http.services.blackbox.loadbalancer.server.port: "9115"
{% if common_traefik_tls %}
      traefik.http.routers.blackbox.tls: "true"
{% endif %}
{% if common_traefik_tls and common_traefik_certresolver != "none" %}
      traefik.http.routers.blackbox.tls.certresolver: "{{ common_traefik_certresolver }}"
      traefik.http.routers.blackbox.tls.domains[0].main: "{{ monitoring_blackbox_traefik_address }}"
{% endif %}

  grafana:
    image: "{{ monitoring_grafana_docker_image }}"
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: "grafana"
    networks:
      - default
      - traefik_proxy
    mem_limit: 512M
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "grafana_dashboards:/var/lib/grafana/dashboards/"
      - "grafana_plugins:/var/lib/grafana/plugins/"
      - "./grafana_providers.yml:/etc/grafana/provisioning/dashboards/providers.yml"
      - "./grafana_datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml"
{% if monitoring_grafana_ldap_toml is defined %}
      - "./grafana_ldap.toml:/etc/grafana/ldap.toml"
{% endif %}
      - "./grafana_dashboards:/var/lib/grafana/dashboards/ansible/"
    environment:
      TZ: "America/New_York"
      PHP_TZ: "America/New_York"
    links:
      - prometheus
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik_proxy"
      traefik.http.routers.grafana.rule: "Host(`{{ monitoring_grafana_traefik_address }}`)"
      traefik.http.services.grafana.loadbalancer.server.port: "3000"
{% if common_traefik_tls %}
      traefik.http.routers.grafana.tls: "true"
{% endif %}
{% if common_traefik_tls and common_traefik_certresolver != "none" %}
      traefik.http.routers.grafana.tls.certresolver: "{{ common_traefik_certresolver }}"
      traefik.http.routers.grafana.tls.domains[0].main: "{{ monitoring_grafana_traefik_address }}"
{% endif %}
    env_file: grafana.env
